[package]
name = "prime_sieve_factorial"
version = "0.1.0"
authors = ["fajara <fajarakurniawan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.1.2"
